version: '3.4'
services:
  lm-calibr-humble-workspace:
    privileged: true
    container_name: lm-calibr-humble-container
    build:
      context: .
    image: lm-calibr-humble-workspace
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ${PWD}:/root/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /dev:/dev
    command: tail -f /dev/null
    network_mode: "host"