# Noise random seed
random_seed: 0

# Currently only supports livox_ros_driver/CustomMsg type
lidar_topic: /livox/lidar
encoder_topic: /joint_states

# Skip the first few seconds of data to remove dynamic objects
rosbag_skip: 0.0
# If accumulated angle exceeds threshold
# discard remaining data to prevent excessive point cloud
angle_threshold: 12.57 # default 4 pi

# Maximum number of LM optimization iterations
max_iter: 50
# Downsampling rate for raw point cloud
downsample_size: 0.1
# Initial size of voxel_map
max_voxel_size: 1.0
# Number of layers in voxel_map = max_layer + 1
max_layer: 2
# Plane threshold for each layer of voxel_map
eigen_threshold: [0.1, 0.1, 0.1]

# for Omni LiDAR
DH_type: 0 
gt_extrinsic:
  d_1: 0.5
  a_1: 0.0
  phi_1: 0.523598776
  theta_2: -1.57079633
  d_2: 0.1
  a_2: 0.0
  phi_2: 0.0

bag_path:
  - "/root/workspace/data/calib_mid360_ntu"
  - "/root/workspace/data/calib_mid360_cave"
  - "/root/workspace/data/calib_mid360_bg"

# # for Non-Omni LiDAR
# DH_type: 1 
# gt_extrinsic:
#   d_1: 0.5
#   a_1: 0.0
#   phi_1: 1.57079633
#   theta_2: 0.0
#   d_2: 0.0
#   a_2: 0.5
#   phi_2: -1.57079633

# bag_path:
#   - "/root/workspace/data/calib_avia_ntu"
#   - "/root/workspace/data/calib_avia_cave"
#   - "/root/workspace/data/calib_avia_bg"